---

- name: Configurar y asegurar MariaDB en Ubuntu

  hosts: ubuntu

  become: yes

  vars:

    db_user: "user"

    db_password: "Servidor1"

    db_name: "ToDo"

    mysql_root_password: "Servidor1"


  tasks:

    - name: Configurar el intérprete de Python

      set_fact:

        ansible_python_interpreter: /usr/bin/python3.12


    - name: Actualizar la lista de paquetes

      apt:

        update_cache: yes


    - name: Instalar MariaDB

      apt:

        name: mariadb-server

        state: present

