---

- name: Configurar MariaDB en el servidor Ubuntu

  hosts: ubuntu

  become: yes

  vars:

    mariadb_root_password: "Servidor1"

    app_database_name: "ToDo"

    app_user: "user"

    app_user_password: ""

    mysql_bind_address: "0.0.0.0"


  tasks:

    - name: Actualizar repositorios APT

      apt:

        update_cache: yes

        cache_valid_time: 3600


    - name: Instalar MariaDB Server

      apt:

        name: mariadb-server

        state: present


    - name: Ejecutar mysql_secure_installation

      command: |

        mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{{ mariadb_root_password }}');"

        mysql -u root -p{{ mariadb_root_password }} -e "DELETE FROM mysql.user WHERE User='';"

        mysql -u root -p{{ mariadb_root_password }} -e "DROP DATABASE IF EXISTS test;"

        mysql -u root -p{{ mariadb_root_password }} -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"

        mysql -u root -p{{ mariadb_root_password }} -e "FLUSH PRIVILEGES;"


    - name: Crear base de datos para la aplicación

      mysql_db:

        name: "{{ app_database_name }}"

        state: present


    - name: Crear usuario de aplicación

      mysql_user:

        name: "{{ app_user }}"

        password: "{{ app_user_password }}"

        priv: "{{ app_database_name }}.*:ALL"

        host: "%"

        state: present


    - name: Asegurarse de que el servicio MariaDB está activo

      service:

        name: mariadb

        state: started

        enabled: yes


    - name: Permitir acceso a MariaDB a través del firewall

      ufw:

        rule: allow

        port: 3306

        proto: tcp


    - name: Configurar MariaDB para permitir conexiones remotas

      lineinfile:

        path: /etc/mysql/mariadb.conf.d/50-server.cnf

        regexp: '^bind-address'

        line: "bind-address = {{ mysql_bind_address }}"

        state: present

      notify: Reiniciar MariaDB


  handlers:

    - name: Reiniciar MariaDB

      service:

        name: mariadb

        state: restarted

