---

- name: Configurar y asegurar MariaDB en Ubuntu
  hosts: ubuntu
  become: yes
  vars:
    db_user: "user"
    db_password: "Servidor1"
    db_name: "ToDo"
    db_root_password: "Servidor1"

  tasks:
    - name: Configurar el intérprete de Python
      set_fact:
        ansible_python_interpreter: /usr/bin/python3.12

    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Instalar MariaDB y herramientas relacionadas
      apt:
        name:
          - mariadb-server
          - mariadb-client

        state: present

    - name: Verificar si mysql_secure_installation está instalado
      command: which mysql_secure_installation
      register: mysql_secure_installation_path
      changed_when: false

    - name: Mostrar ruta de mysql_secure_installation
      debug:
        msg: "La ruta de mysql_secure_installation es {{ mysql_secure_installation_path.stdout }}"

#    - name: Cambiar bind
#      ansible.builtin.lineinfile:
#        path: /etc/mysql/my.cnf
#        regexp: '^#bind-address'
#        line: '[mysqld]\nbind-address = 0.0.0.0'
#        state: present

    - name: Cambiar bind
      ansible.builtin.blockinfile:
        path: /etc/mysql/my.cnf
        marker: '# ANSIBLE'
        state: present
        block: |
          [mysqld]
          bind-address = 0.0.0.0


    - name: Instalar pip
      apt:
        name: pip
        state: present

    - name: Instalar pip3
      apt:
        name: python3-pip
        state: present

    - name: Asegurar pymysql
      become: true
      apt:
        name: python3-pymysql
        state: present

    - name: Copiar SQL
      ansible.builtin.copy:
        src: "/home/user/obligatorio/ansible/files/db.sql"
        dest: "~/db.sql"

    - name: Aplicar SQL
      mysql_db:
        state: import
#        login_user: "root"
#        login_password: ""
#        login_host: "127.0.0.1"
        login_unix_socket: /run/mysqld/mysqld.sock
        name: "todo"
        target: "~/db.sql"

    - name: Reiniciar servicio
      service:
        name: mariadb
        state: restarted

